# Generated by Django 5.0.4 on 2024-06-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_about_journal_name_en_about_journal_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='editorial',
            name='journal_edi_created_a35c6f_idx',
        ),
    ]
