# Generated by Django 5.0.4 on 2024-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['-created_at'], name='journal_edi_created_a35c6f_idx'),
        ),
    ]
